Add memset_s to fix buffer overflow for memset function in sqlite3
microsoft/cpp_client_telemetry pull request #1286
Opened 2024-07-11 07:36 UTC by ShrutiJaiswal1494

Add memset_s to fix buffer overflow for the traditional memset function in sqlite3 library as part of the CodeQL sanity checks.

2024-07-11 23:40 UTC, lalitb commented on sqlite/sqlite3_debug.c
> +** Please do not remove this method as it is required for the CodeQL sanity checks.
nit - please remove this comment regarding CodeQL, as this is specific to the CodeQL configuration internally used, and doesn't go well in open source code.

2024-07-11 23:47 UTC, lalitb commented on sqlite/sqlite3_debug.c
> +
please move this function in separate header file, and include that header file here. Also I believe we need to update `sqlite3_retail` with similar changes, so the header file can be used across both.

2024-07-12 00:01 UTC, lalitb commented on sqlite/sqlite3_debug.c
> +    sizeof(PgHdr) - offsetof(PgHdr, pDirty));
Should we invoke this conditionally under a macro? Although these bound validations enhance safety and prevent buffer overflows, they also introduce a slight performance overhead, which may not be acceptable for applications with strict performance requirements.  This is particularly relevant in scenarios where sqlite is already ensuring that calling `memset` does not result in an overflow. Something like:

```cpp
#if USE_ONEDS_SECURE_MEM_FUNCTIONS 
    memset_s(&pPgHdr->pDirty, sizeof(PgHdr) - offsetof(PgHdr, pDirty), 0,
             sizeof(PgHdr) - offsetof(PgHdr, pDirty));
#else
    memset(&pPgHdr->pDirty, 0, sizeof(PgHdr) - offsetof(PgHdr, pDirty));
#endif
```

2024-07-16 21:22 UTC, lalitb commented
@ShrutiJaiswal1494 - Can you address the open comments? It was agreed in today's community meeting that the changes can proceed.

2024-07-22 19:01 UTC, lalitb requested changes
As mentioned in the comments.

2024-07-22 19:26 UTC, ThomsonTan commented on sqlite/sqlite3_debug.c
> +    sizeof(PgHdr) - offsetof(PgHdr, pDirty));
Probably good to guard all the new code within the feature flag like `USE_ONEDS_SEURE_MEM_FUNCTIONS`, or there will be unused function of memset_s left.

2024-07-23 22:51 UTC, lalitb approved these changes
LGTM. Thanks for the PR.

2024-07-23 22:58 UTC, ThomsonTan approved these changes

2024-07-24 05:23 UTC, lalitb commented
Doing force merge, as the mac CI is failing for older virtual images

2024-07-24 05:23 UTC, merged